import sys
import os
import argparse
import shutil

parser = argparse.ArgumentParser(description='Arrange data from DiscoFaceGAN')

parser.add_argument("--indir", default="/workspace/DiscoFaceGAN/generate_images", type=str, help='Directory containing images generated by DiscoFaceGAN')
parser.add_argument("--traindir", default="/workspace/fairDL/data/synthface", type=str, help='Training directory for fairDL analysis')
parser.add_argument("--testdir", default="/workspace/fairDL/data/synthfacetest", type=str, help='Testing directory for fairDL analysis')

def main():
    global args
    args = parser.parse_args()

    for filename in os.listdir(args.indir):
        dir_num = int(str.split(filename, '_')[0])
        if dir_num < 2000:
            outdir = os.path.join(args.traindir, 'id_'+str(dir_num))
            os.makedirs(outdir, exist_ok=True)
            src_file = os.path.join(args.indir, filename)
            tgt_file = os.path.join(outdir, filename)
        else:
            outdir = os.path.join(args.testdir, 'id_'+str(dir_num))
            os.makedirs(outdir, exist_ok=True)
            src_file = os.path.join(args.indir, filename)
            tgt_file = os.path.join(outdir, filename)
        shutil.copy(src_file, tgt_file)


if __name__ == "__main__":
    main()